-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 12, 2019 at 06:15 AM
-- Server version: 10.4.8-MariaDB
-- PHP Version: 7.3.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `register_system`
--

-- --------------------------------------------------------

--
-- Table structure for table `course`
--

CREATE TABLE `course` (
  `Course_ID` int(11) NOT NULL,
  `C_Name` varchar(300) NOT NULL,
  `C_Description` varchar(800) NOT NULL,
  `C_Code` varchar(45) NOT NULL,
  `C_CreditAmt` double NOT NULL,
  `CDeptID` int(11) NOT NULL,
  `C_DeptName` varchar(60) NOT NULL,
  `CourseLevel` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `course`
--

INSERT INTO `course` (`Course_ID`, `C_Name`, `C_Description`, `C_Code`, `C_CreditAmt`, `CDeptID`, `C_DeptName`, `CourseLevel`) VALUES
(40000, 'Blood, Hematopoiesis & Lymphatics', 'This course introduces students to the physiology, embryogenesis and diseases of the blood. Specific emphasis is on disease states and how these reveal basic system characteristics useful in diagnosis and treatment.', 'MED 101', 3, 127, 'Medical', 1),
(40001, 'Clinical Medicine I', 'This course teaches the basic clinical skills of interviewing, physical exam and diagnostic clinical thinking under the supervision of trained SPs and physicians.', 'MED 102', 3, 127, 'Medical', 1),
(40002, 'Design & Analysis of Clinical Research', 'This course will prepare the student to understand principles of biostatistics and epidemiology. Topics will include research design; statistical and epidemiologic measures of disease burden, distribution, and association; and methods of statistical inference and hypothesis testing.', 'MED 103', 3, 127, 'Medical', 1),
(40003, 'Foundations of Medicine\r\n', 'This course presents foundational concepts of human genetics, molecular biology, protein structure and function, cell biology, carcinogenesis, pharmacokinetics, pharmacodynamics, drug metabolism, cell physiology, autonomic nervous system, cellular electrophysiology, inflammation, wound healing, fluid balance, hemodynamics, clinical laboratory methods, and drugs affecting the neuromuscular and autonomic nervous systems.', 'MED 104', 3, 127, 'Medical', 1),
(40004, 'Gastrointestinal & Hepatobiliary', 'This course highlights and integrates the fundamental concepts in embryology, histology, gross anatomy, physiology, pathology, pathophysiology and pharmacology of the gastrointestinal tract', 'MED 201', 3, 127, 'Medical', 1),
(40005, 'Human Structure', 'This course includes the macroscopic study of regions, systems and organs of the human body. Students will use this course as a basis for understanding the depths of human biology required in a modern practice of clinical medicine.', 'MED 202', 3, 127, 'Medical', 1),
(40006, 'Immunology, Microbiology & Integument', 'This course will present the normal development, structure, function, and diseases of the immune system. In addition, basic principles of microbiology and antimicrobial therapy will be covered as well as infectious diseases of the integument, including distinguishing characteristics of the infectious agent, epidemiology, clinical manifestations, pathogenesis, and treatment and prevention.', 'MED 203', 3, 127, 'Medical', 1),
(40007, 'Lifestyle Medicine and Health Promotion', 'This course provides first-year medical students within the community medicine track with the foundational knowledge of lifestyle medicine, including its applications for advancing personal, patient and population health.', 'MED 301', 3, 127, 'Medical ', 1),
(40008, 'Patients, Physicians, and Society', 'This course is a broad course covering healthcare economics, behavioral factors in medicine and disease, normal human development, cultural factors in the practice of medicine and substance abuse.', 'MED 302', 3, 127, 'Medical', 1),
(40009, 'Patients, Physicians, and Society', 'This course is a broad course covering healthcare economics, behavioral factors in medicine and disease, normal human development, cultural factors in the practice of medicine and substance abuse.', 'MED 303', 3, 127, 'Medical', 1),
(40010, 'Cardiovascular, Respiratory & Renal Systems', 'This course presents the normal physiological mechanisms of the cardiovascular, respiratory, and renal systems. The course will then present the most common pathological conditions and clinical presentations involving these systems, with an emphasis on how the pathology affects the normal systems. Finally, treatments for the pathological conditions will be presented.', 'MED 401', 3, 127, 'Medical', 2),
(40011, 'Clinical Medicine', 'This course teaches the basic clinical skills of interviewing, physical exam and diagnostic clinical thinking under the supervision of trained SPs and physicians.', 'MED 402', 3, 127, 'Medical', 2),
(40012, 'Neurosciences', 'This course introduces students to diverse aspects of the nervous system clinically relevant to neurologic and psychiatric conditions. Focus is on brain structure, function, pathways, and major pathologic conditions.', 'MED 403', 3, 127, 'Medical', 2),
(40013, 'Patients, Physicians, and Society', 'The foundations of this course are that ethics contributes to high quality patient care and professional behavior; that knowledge of ethics enables medical trainees to become better physicians; and that ethics can be taught, learned, and evaluated along with the general corpus of medical knowledge.', 'MED 404', 3, 127, 'Medical', 2),
(50000, 'Introduction to Biology', 'An introduction to cellular structure and function, to biological molecules, bioenergetics, to the genetics of both prokaryotic and eukaryotic organisms, and to the elements of molecular biology.', 'BIO 101', 3, 125, 'Biology', 1),
(50001, 'Evolutionary Biology', 'The first principles of evolutionary theory, classification, ecology, and behavior; a phylogenetic synopsis of the major groups of organisms from viruses to primates.', 'BIO 102', 3, 125, 'Biology', 1),
(50002, 'Introductory Biology Lab', 'Students gain hands-on experience and learn the theoretical basis of lab techniques common to a variety of biological disciplines such as biochemistry, molecular biology, cell biology, and bioinformatics.', 'BIO 102A', 2, 125, 'Biology', 1),
(50003, 'Human Genetics in Modern Society', 'Explores the makeup and structure of human genetical lines.', 'BIO 103', 3, 125, 'Biology', 1),
(50004, 'Human Neuorology', 'Introduction to basic human neuroscience leading to a discussion of brain diseases classified under the rubric Dementia.', 'BIO 104', 3, 125, 'Biology', 1),
(50005, 'Quantitative Biology Project Lab', 'Course covers two important aspects: (1) interdisciplinary and research-based education and (2) teaching fundamental experimental and computational skills in quantitative studies of living systems. ', 'BIO 105', 3, 125, 'Biology', 1),
(50006, 'Genomics Research Initiative Lab I', 'Students will isolate bacterial viruses or other organisms from the environment and characterize them by methods including electron microscopy and nucleic acid analysis.', 'BIO 201', 3, 125, 'Biology', 1),
(50007, 'Undergraduate Workshops', 'The workshops will be restricted to lower-division undergraduates. The course will introduce students to the methods of scientific research and to a variety of research topics in the biological/biomedical sciences.', 'BIO 202', 3, 125, 'Biology ', 1),
(50008, 'Structural Biochemistry', 'The structure and function of biomolecules. Includes protein conformation, dynamics, and function; enzymatic catalysis, enzyme kinetics, and allosteric regulation; lipids and membranes; sugars and polysaccharides; and nucleic acids.', 'BCH 301', 3, 125, 'Biochemistry', 2),
(50009, 'Metabolic Biochemistry', 'Energy-producing pathways–glycolysis, the TCA cycle, oxidative phosphorylation, photosynthesis, and fatty acid oxidation; and biosynthetic pathways–gluconeogenesis, glycogen synthesis, and fatty acid biosynthesis.', 'BCH 302', 3, 125, 'Biochemistry', 2),
(50010, 'Biochemical Techniques', 'Introductory laboratory course in current principles and techniques applicable to research problems in biochemistry and molecular biology. ', 'BCH 301A', 2, 125, 'Biochemistry', 2),
(50011, 'Nutrition', 'Elaborates the relationship between diet and human metabolism, physiology, health, and disease. ', 'BCH 303', 3, 125, 'Biochemistry', 2),
(50012, 'Chemistry of Biological Interactions', 'Nearly all interactions between organisms, including host-pathogen interactions and mate attraction, have a chemical basis. Plants and microorganisms are the dominant life forms on earth and remain a major source of pharmaceutical leads. Students in this course will utilize biochemical methods to extract, fractionate, and analyze plant and microbial compounds of medicinal and ecological significance including antibiotics, growth regulators, toxins, and signaling molecules.', 'BCH 304', 3, 125, 'Biochemistry', 2),
(50013, 'Advanced Topics in Modern Biology: Biochemistry', 'Students are expected to actively participate in course discussions, read, and analyze primary literature.', 'BCH 305', 3, 125, 'Biochemistry', 2),
(50014, 'Molecular Biology', '>Molecular basis of biological processes, emphasizing gene action in context of entire genome. Chromosomes and DNA metabolism: chromatin, DNA replication, repair, mutation, recombination, transposition.', 'BGE 401', 3, 125, 'Biogenetics', 2),
(50015, 'Molecular Biology Laboratory', 'Techniques in microbial physiology, microbial genomics, microbial evolution, and microbial ecology will be used to explore the role of microbes in industry, health, and the environment.', 'BGE 401A', 3, 125, 'Biogenetics', 2),
(50016, 'Molecular Basis of Human Disease', 'An examination of the molecular basis of human diseases.', 'BGE 402', 3, 125, 'Biogenetics', 2),
(50017, 'Virology', 'An introduction to eukaryotic virology, with emphasis on animal virus systems', 'BGE 403', 3, 125, 'Biogenetics', 2),
(50018, 'Pharmacology', 'Basics of pharmacology such as drug absorption, distribution, metabolism, and elimination.', 'BGE 404', 3, 125, 'Biogenetics', 2),
(50019, 'Microbial Genetics', 'Course will consider the organization and function of prokaryotic genomes including content, DNA supercoiling, histone-like proteins, chromosomal dynamics (short-term and long-term), extrachromosomal elements, bacterial sex, transduction, transformation, mobile elements (transposon), epigenetic change, adaptive and directed mutation', 'BGE 405', 3, 125, 'Biogenetics', 2),
(50020, 'Medical Microbiology', 'Encompasses the increasingly important areas of viral, bacterial, and parasitic diseases and understanding the complex interaction between humans and infectious agents.', 'BGE 405', 3, 125, 'Biogenetics', 2),
(50021, 'Quantitative Principles in Biology', 'Course considers problems in biology that were solved using quantitative biology approaches. Problems will range from the molecular to the population level.', 'BGE 406', 3, 125, 'Biogenetics', 2),
(50022, 'Bioinformatics Laboratory', 'Bioinformatics is the analysis of big data in the biosciences. This course provides a hands-on introduction to the computer-based analysis of biomolecular and genomic data.', 'BGE 406A', 2, 125, 'Biogenetics', 2),
(50023, 'Structural Biology of Viruses', 'An introduction to virus structures, how they are determined, and how they facilitate the various stages of the viral life cycle from host recognition and entry to replication, assembly, release, and transmission to uninfected host cells.', 'BGE 407', 3, 125, 'Biogenetics', 2),
(60000, 'Drawing Fundamentals', 'This course investigates concepts and practices of drawing from observation, memory and imagination, while building individual skills and awareness of composition, expression and visual communication.', 'ART 101', 3, 128, 'Art', 1),
(60001, 'Self and Representation', 'This course investigates concepts and design principles of two-dimensional processes of painting and printmaking. Conceptually, the assignments are driven by an exploration of art through personal narratives, issues of identity, and as a vehicle for spiritual and psychological transformation. ', 'ART 102', 3, 128, 'Art', 1),
(60002, 'Visual Theory and Aesthetics', 'Introduces and explores visual, aesthetic, and critical theory, and the social and cultural dynamics that inform and influence contemporary art making.', 'ART 103', 3, 128, 'Art', 1),
(60003, 'Introduction to Graphic Design', '>A critical approach to graphic design is indispensable in the social worlds it mediates. This course develops the designer capacity for graphic thought through semantic and syntactic explorations of visual form. Through a variety of studio exercises and assignments, students develop their own design processes to discover the ways in which graphic design engages in visual knowledge production.', 'ART 201', 3, 128, 'Art', 1),
(60004, 'Introduction to Media and Letterpress', 'In intaglio printmaking the image is incised into the plate and the incised line holds the ink to be printed on paper. It is the opposite of relief printmaking. Collagraph is similar to intaglio but uses inexpensive materials to build the plate to be printed.', 'ART 202', 3, 128, 'Art', 1),
(60005, 'Introduction to Print Media', 'In intaglio printmaking the image is incised into the plate and the incised line holds the ink to be printed on paper. It is the opposite of relief printmaking. Collagraph is similar to intaglio but uses inexpensive materials to build the plate to be printed.', 'ART 203', 3, 128, 'Art', 1),
(60006, 'Drawing Concepts', 'First semester of a two-semester sequence of drawing courses focusing on the language, materials and concepts of drawing as foundation for all the visual arts. Emphasizes the development of perceptual, analytical, and structural drawing skills while simultaneously working with idea development.', 'ART 204', 3, 128, 'Art', 1),
(60007, 'Introduction to Photography', 'This studio course examines the historical, conceptual, and practical developments of the art of photography as embodied in the use of digital image-making technologies under natural and ambient lighting. ', 'ART 205', 3, 128, 'Art', 1),
(60008, 'Basic Painting', '>Covers basic methods and materials in oil painting; including traditional and current approaches to form, color, and pictorial organization. Varied course structure includes direct interpretation of subject matter, as well as conceptually based visual problems.', 'ART 206', 3, 128, 'Art', 1),
(60009, 'Pictorial Structure', 'Addresses the formal and conceptual aspects of 2D artwork. Art from the past and present is viewed, discussed, and utilized as a starting point for student-driven assignments.', 'ART 301', 3, 128, 'Art', 1),
(60010, 'Typographic Form', 'This course introduces the basic terminology, concepts and practices of communicating with typography. It engages the construction of typography from the scale of the letterform to the word, the line, the paragraph and the page/screen.', 'ART 302', 3, 128, 'Art', 1),
(60011, 'Introduction to Print Media', 'Prized for its subtle effects and evocative surfaces, lithography is particularly well suited for artists who like to draw or use photographic/digital montage strategies to construct images.', 'ART 303', 3, 128, 'Art', 1),
(60012, 'Introduction to Sculpture', 'Paradigms of space, from map to model, shift radically from epoch to epoch. Reflecting these shifts, sculpture since Minimalism, has increasingly redefined its notion of \'form\' and \'objectness\' to include the surrounding perceptual space, temporal practices, and the socio-political constituents of space.', 'ART 304', 3, 128, 'Art', 1),
(60013, 'Introduction to Digital Art', ' Surveys, in a hands-on fashion, the rich and unique resources the computer offers the artist/designer. Includes computer basics, letter manipulation, drawing and painting metaphors, image processing, 3-D modeling, sound/image synthesis, interactive scripting, and animation.', 'ART 401', 3, 128, 'Art ', 2),
(60014, 'Individual Paintings Explorations', 'Encourages individual creative research through a consistent exploration of themes, concepts, processes and media towards a cohesive body of work. This course also investigates a variety of possible ways for installation and exhibition.', 'ART 402', 3, 128, 'Art', 2),
(60015, 'Graphic Systems', 'This course introduces students to a structural approach and systemic principles in the construction and application of graphic form. Students learn to create graphic systems by exploring among other things, graphic identity systems, icon/symbolic -systems and graphic navigation systems.', 'ART 403', 3, 128, 'Art', 2),
(60016, 'Web Design', 'This course focuses on aspects of professional front-end web design technologies and processes, including hand-coding HTML5/CSS3, simple JavaScript, WordPress, responsive design for mobile devices, integration with social media channels, information architecture, and user experience design.', 'ART 404', 3, 128, 'Art', 2),
(60017, 'Typographic Systems', 'Building on the concepts and skills developed in Typographic Form, this course introduces students to a systematic approach to the use of typography in graphic design towards building a capacity to work with complex sets of information. The assignments in this course develop and exercise the student¿s sense of structural logic, style and syntactics.', 'ART 405', 3, 128, 'Art', 2),
(60018, 'Computer Motion Imaging', 'Explores with computer graphics, the expressive and informative impact of real time and frame/cell animation: pixilation; metamorphosis; interaction of synthesized actors with backgrounds; the dynamics of sound/image synthesis; and time-space structures\' application to computer animation.', 'ART 406', 3, 128, 'Art', 2),
(70000, 'Concepts in Computer Science', 'Fundamental concepts in program design, data structures, algorithms, analysis and a survey of topics in CS. Not open to Computer Science majors.', 'CS 100', 3, 129, 'Computer Science', 1),
(70001, 'Computer Science I', 'Problem solving techniques, order analysis and notation, abstract data types, and recursion.', 'CS 101', 3, 129, 'Computer Science', 1),
(70002, 'Programming I', 'This introductory course teaches the fundamental concepts of programming languages by use of the popular Java language. The topics cover fundamental principles of programming, including data types, program control and decisions, loops, string manipulations, procedures, arrays, software testing, and debugging.', 'CS 102', 3, 129, 'Computer Science', 1),
(70003, 'Programming 2', 'This course builds on the Introduction to Programming 1 course and teaches a more highly developed Java programming language with features beyond the basic concepts covered in the first programming course, preparing students for professional software development builds on this work in several directions. A large part of the course will be devoted to more advanced building blocks such as recursion, linked data structures, and Java’s Collection Framework.', 'CS 102', 3, 129, 'Computer Science', 1),
(70004, 'Databases', 'This course introduces the fundamental concepts necessary for designing, using and implementing database systems.', 'CS 201', 3, 129, 'Computer Science', 1),
(70005, 'Computer Communications and Networks', 'This course will introduce the basic concepts of communication networks, including the OSI model and different types of communication protocols, including the Internet Protocol (TCP/IP protocol). The course will also cover the key concepts and structures of the Internet.', 'CS 202', 3, 129, 'Computer Science', 1),
(70006, 'Operating Systems', 'This course provides an applied introduction to commercial operating systems. It is intended for intermediate students who have basic programming skills. Key concepts of computer systems and operating systems are introduced, as well as the communications and linkages associated with computer systems. Operating systems that are introduced include Microsoft Windows and UNIX/Linux.', 'CS 203', 3, 129, 'Computer Science', 1),
(70007, 'Software Engineering', 'This course focuses on the engineering process requirements, including identification of stakeholders, requirements elicitation techniques such as interviews and prototyping, analysis fundamentals, requirements specification, and validation.', 'CS 204', 3, 129, 'Computer Science', 1),
(70008, 'Data Structures', 'This course introduces the fundamental concepts of data structures and the algorithms that proceed from them. Although this course has a greater focus on theory than application the assignments, examples, and cases introduced throughout the course help to bring the gap between theoretical concepts and real world problem solving. We will be using a software tool that will enhance our understanding of the operation and function of the data structures and algorithms explored throughout the course by visually animating examples of data structures and algorithms so that we can understand their operation.', 'CS 205', 3, 129, 'Computer Science', 1),
(70009, 'Web Programming', 'This course introduces students to fundamental concepts and issues surrounding software development for programs that operate on the web and the internet such as static and dynamic content, dynamically served content, web development processes, and security.', 'CS 206', 3, 129, 'Computer Science', 1),
(70010, 'Introduction to Discrete Structures', 'This is a rigorous introduction to some topics in mathematics that underlie areas in computer science and computer engineering, including graphs and trees, spanning trees, and matchings; the pigeonhole principle, induction and recursion, generating functions, and discrete probability proofs (time permitting). The course integrates learning mathematical theories with applications to concrete problems from other disciplines using discrete modeling techniques. Student groups will be formed to investigate a concept or an application related to discrete mathematics, and each group will report its findings to the class in a final presentation.', 'CS 207', 3, 129, 'Computer Science', 1),
(70011, 'Advanced Networking and Data Security', 'This course explores the basic components and design principles of advanced broadband networks (wireline and wireless) and how they enable essential services such as mobility, and secure data storage, processing and transmission.', 'CS 301', 3, 129, 'Computer Science', 2),
(70012, '>Mobile Applications', 'The course explores concepts and issues surrounding information system applications to real-time operating systems and wireless networking systems.', 'CS 302', 3, 129, 'Computer Science', 2),
(70013, 'Web Design ', 'This course focuses on aspects of professional front-end web design technologies and processes, including hand-coding HTML5/CSS3, simple JavaScript, WordPress, responsive design for mobile devices, integration with social media channels, information architecture, and user experience design. ', 'CS 303', 3, 129, 'Computer Science', 2),
(70014, 'Artificial Intelligence', 'This course will cover current concepts and techniques in artificial intelligence, including “reasoning”, problem solving, and search optimization. ', 'CS 304', 3, 129, 'Computer Science', 2),
(70015, 'Data Mining', 'This course presents an introduction to current concepts in machine learning, knowledge discovery, and data mining. Approaches to the analysis of learning algorithm performance will also be discussed and applied.', 'CS 305', 3, 129, 'Computer Science', 2),
(80000, 'Introduction to Business Management', 'This course is an introduction to the field of business management. Topics include developing mission, vision and values, organizational culture, leadership, decision-making, organizational behavior, motivation, and human resource management.', 'BUS 101', 3, 126, 'Business', 1),
(80001, 'Basic Accounting', 'This course serves as an introduction to the basic theory, principles and techniques of contemporary financial accounting. Topics include the accounting cycle and the preparation of financial statements.', 'BUS 102', 3, 126, 'Business', 1),
(80002, 'MicroEconomics', 'This course introduces the economic analysis of the interactions between households, businesses and government with regard to allocation of goods, services and resources. In this course, we will learn about basic elements of consumer and firm behavior, different market structures and their effects on welfare, and the direct and indirect role of the government in determining economic outcomes.', 'BUS 103', 3, 126, 'Business', 1),
(80003, 'Macroeconomics', 'This course provides a solid overview of the field of macroeconomics with the intent to develop a general understanding and appreciation of the factors and methods used to manage macroeconomic policy and the impact of these policies on the global economy. This course will help you to understand how a nation’s economy works and how macroeconomic policy impacts a nation’s economy.', 'BUS 103', 3, 126, 'Business', 1),
(80004, 'Business Communications', 'The purpose of this course is to build an understanding of effective uses of English in a business environment and to develop strong core business communication skills. This course will introduce and enhance the varying modes of English communication in the business environment and will also focus on when to use these varying modes, depending on the situation.', 'BUS 201', 3, 126, 'Business', 1),
(80005, 'Principles of Marketing', 'This course provides an introduction to the field of marketing where students develop a general understanding and appreciation of the factors and methods involved in marketing a variety of goods and services. Topics include consumer needs, segmentation, target marketing, positioning, pricing, distributing, and promoting goods and services.', 'BUS 202', 3, 126, 'Business', 1),
(80006, 'Principles of Finance', 'This course provides a broad understanding of basic principles in the area of finance. The course introduces techniques for effective financial decision-making and helping managers to maximize shareholders’ wealth.', 'BUS 203', 3, 126, 'Business', 1),
(80007, 'Financial Accounting', 'This course continues the study of accounting begun by the students during their Basic Accounting course. This course emphasizes accounting for liabilities, accounting for equity, and corporate forms of ownership. Topics include responsibility accounting, budgets, cost control, and standard costing procedures and analysis of variances. ', 'BUS 301', 3, 126, 'Business', 1),
(80008, 'Entrepreneurship', 'This course provides an introduction to entrepreneurship and the dynamics of starting/owning a business. This course is designed to assist students with the knowledge and skills entrepreneurs need to start and/or manage a small business. It will help you understand the steps involved in the process of the creation/development of business ideas and turning those ideas into a successful business model.', 'BUS 302', 3, 126, 'Business', 1),
(80009, 'Managerial Accounting', 'This course is a continuation of Financial Accounting with focus shifted to the internal needs of managers. The course offers students an understanding of managerial accounting techniques used in today’s modern business world.', 'BUS 303', 3, 126, 'Business', 1),
(80010, 'Business Law and Ethics', 'This course introduces the student to law and ethics as they apply in a business environment. The intent of this course is to develop in the student a general understanding of basic legal principles and how they affect the conduct of business on a practical level. While common law legal systems and that of the United States in particular are used to demonstrate the interaction of law and business, the principles introduced here assist in developing a general approach to business law and ethics. Topics include an introduction to law in general, litigation and alternatives to litigation, criminal law, torts and contracts, property law, employment law and business ethics.', 'BUS 304', 3, 126, 'Business', 1),
(80011, 'Business and Society', 'This course explores the inter-relationships between business and society, including the tensions between various stakeholders and the growing pressures to approach business with corporate responsibility and sustainability as primary underlying influences. With rapidly changing technology and globalization, we must strategize our business decisions with far greater insight and conscientiousness than ever before. This course takes a look at business and society relationships from various global perspectives, including developing countries and societies, and different cultural norms and beliefs.', 'BUS 305', 3, 126, 'Business', 1),
(80012, 'Entrepreneurship 2', 'This course continues where Entrepreneurship ended and addresses entrepreneurship in international markets. The key success factors in creating a new internationally oriented business venture will be examined from the perspective of the entrepreneur.', 'BUS 401', 3, 126, 'Business', 2),
(80013, 'Organizational Behavior', 'This course focuses on the examination of research and theory of factors that influence the way members of an organization behave. Topics include the behavior of employees, work groups and supervisors, effective organizational communication, handling of change in the organization, and the goals and structure of an organization.', 'BUS 402', 3, 126, 'Business', 2),
(80014, 'Business Policy and Strategy', 'This course addresses the formulation, implementation, monitoring and control of business strategies and supporting organizational policies. Students learn to evaluate the comprehensive business enterprise through an integrated view of the various functional disciplines. This course attempts to develop the conceptual and abstract skills required by leaders of businesses in a competitive environment in order to understand business issues and challenges from the perspective of all functional managers.', 'BUS 403', 3, 126, 'Business', 2),
(80015, 'Principles of Finance 2', 'This course expands on concepts from Principles of Finance 1 to provide greater depth of core issues including valuation, cost of capital, capital budgeting, estimating cash flows, capital structure, dividends, forecasting, and working capital management. Case studies and information resources will be utilized to explain how financial theory is applied in real-life situations.', 'BUS 404', 3, 126, 'Business', 2),
(80016, 'Leadership', 'In this course, students will explore organizational leadership theories as well as examine how to strategically lead self and others while fostering a culture of performance. Students will use tools that leverage organizational and individual development. Through an integration of a variety of these tools, strategies, and theories, the students will develop knowledge, skills and attitudes (KSA) necessary in contemporary leadership development.', 'BUS 405', 3, 126, 'Business', 2),
(80017, 'Strategic Management', 'This course explores the relationships between organizations and their environments from a corporate policy perspective. Topics to be discussed include organizational structure and development, competition analysis, long and short-range planning, creating mission and vision statements, implementing goals, performance indicators and evaluation.', 'BUS 406', 3, 126, 'Business', 2),
(90000, 'Pre-Calculus', 'College Calculus', 'MAT 100', 3, 124, 'Math', 0),
(90001, 'Calculus 1', 'Continuity, limits, and the derivative for algebraic, trigonometric, logarithmic, exponential, and inverse functions. Applications to physics, chemistry, and engineering.', '101', 3, 124, 'Math', 0),
(90002, 'Linear Algebra', 'Basic concepts of linear algebra. Matrices, determinants, systems of linear equations, vector spaces, linear transformations, and eigenvalues.', 'MAT 102', 3, 124, 'Math', 0),
(90003, 'Introduction to Statistics', 'Basics of probability, random variables, binomial and normal distributions, central limit theorem, hypothesis testing, and simple linear regression.', 'MAT 103', 3, 124, 'Math', 0),
(90004, 'Calculus 2', 'The definite integral, techniques of integration, and applications to physics, chemistry, and engineering. Sequences, series, and power series', 'MAT 201', 3, 124, 'Math', 0),
(90005, 'Multivariable Calculus', 'Techniques of calculus in two and three dimensions. Vectors, partial derivatives, multiple integrals, line integrals.', 'MAT 202', 3, 124, 'Math', 0),
(90006, 'Linear Methods', 'Linear equations and inequalities, matrices, linear programming with applications to business, probability and discrete random variables.', 'MAT 203', 3, 124, 'Math', 0),
(90007, 'Calculus 3', 'Advanced Calculus', 'MAT 301', 3, 124, 'Math', 0),
(90008, 'Fundamentals of Mathematics', 'Students will learn how to read, understand, devise and communicate proofs of mathematical statements. A number of proof techniques (contrapositive, contradiction, and especially induction) will be emphasized. Topics to be discussed include set theory (Cantor\'s notion of size for sets and gradations', 'MAT 302', 3, 124, 'Math', 0),
(90009, 'Writing in Mathematics', 'Essentially all serious mathematics is written using some variant of the LaTeX software, and developing proficiency with this tool is an important part of the course. We will cover a variety of types of writing related to mathematics, such as: critique of seminar presentations and written articles; ', 'MAT 303', 3, 124, 'Math', 0),
(90010, 'Introduction to Abstract Algebra', '>Introduction to groups, rings, fields, vector spaces, and related concepts. Emphasis on development of careful mathematical reasoning.', 'MAT 304', 3, 124, 'Math', 0),
(90011, 'Complex Variables', 'An introduction to functions of a complex variable. Topics include: Complex numbers, functions of a complex variable and their derivatives (Cauchy-Riemann equations). Harmonic functions. Contour integration and Cauchy\'s integral formula. Liouville\'s theorem, Maximum modulus theorem, and the Fundamental Theorem of Algebra.', 'MAT 305', 3, 124, 'Math', 0),
(90012, 'Number Theory', 'This course is a proof-based introduction to elementary number theory. We will quickly review basic properties of the integers including modular arithmetic and linear Diophantine equations covered in Math 300 or CS250. We will proceed to study primitive roots, quadratic reciprocity, Gaussian integers, and some non-linear Diophantine equations. Several important applications to cryptography will be discussed.', 'MAT 306', 3, 124, 'Math', 0),
(90013, 'Advanced Multivariate Calculus', 'Calculus of several variables, Jacobians, implicit functions, inverse functions; multiple integrals, line and surface integrals, divergence theorem, Stokes\' theorem.', 'MAT 401', 3, 124, 'Math', 0),
(90014, 'Introduction to Discrete Structures', 'This is a rigorous introduction to some topics in mathematics that underlie areas in computer science and computer engineering, including graphs and trees, spanning trees, and matchings; the pigeonhole principle, induction and recursion, generating functions, and discrete probability proofs (time permitting). The course integrates learning mathematical theories with applications to concrete problems from other disciplines using discrete modeling techniques. Student groups will be formed to inves', 'MAT 402', 3, 124, 'Math', 0),
(90015, 'Introduction to Modern Analysis', 'This is the first part of the introduction to analysis sequence (523 and 524). This course deals with basic concepts of analysis of functions mostly on the real line, and we will try to make many of the concepts one learns in calculus rigorous. Covered topics will include series, and sequences, continuity, differentiability, and integration.', 'MAT 403', 3, 124, 'Math', 0),
(90016, 'Linear Algebra for Applied Mathematics', 'Basic concepts (over real or complex numbers): vector spaces, basis, dimension, linear transformations and matrices, change of basis, similarity. Study of a single linear operator: minimal and characteristic polynomial, eigenvalues, invariant subspaces, triangular form, Cayley-Hamilton theorem. Inner product spaces and special types of linear operators (over real or complex fields): orthogonal, unitary, self-adjoint, hermitian. Diagonalization of symmetric matrices, applications.', 'MAT 404', 3, 124, 'Math', 0),
(100000, 'Composition 1', 'Expository writing with emphasis on effective communication and critical thinking. Emphasizing the writing process writing topics are based on selected readings and on student experiences\r\n', 'ENG 101', 3, 130, 'English', 1),
(100001, 'Fundamentals of Oral Communication', 'Communication theory and its application to preparing and delivering public speeches.', 'ENG 103', 3, 130, 'English', 1),
(100002, 'Fundamentals of Technical Presentations', 'Communication theory and its application to preparing and delivering technical information in public speaking situations.\r\n', 'ENG 103', 3, 130, 'English', 1),
(100003, 'Introduction to Humanities', 'The range of ideas, research methods and approaches to scholarship, critical reflection, and creative work in the humanities. \r\n', 'HUM 101', 3, 131, 'Humanities', 1),
(100004, 'Western Civilization', 'A survey of western civilization from ancient to 1648', 'HUM 102', 3, 131, 'Humanities', 1),
(100005, 'Humanistic Tradition', 'An interdisciplinary, multicultural study of the arts and sciences contributed by diverse human traditions to world civilization. Focus is on ancient civilizations and the cultural heritage stemming from them.', 'HUM 103', 3, 131, 'Humanities', 1),
(100006, 'U.S. History: 1492-1877', 'Survey of U.S. History from 1492-187', 'HUM 104', 3, 131, 'Humanities ', 1),
(100007, 'World Civilization', 'A topical approach to the study of the rise and decline of world civilizations from the first attempts to the great civilizations of medieval times.\r\n   ', 'HUM 105', 3, 131, 'Humanities', 1),
(100008, 'General Anthropology', 'An introductory survey of the four major subfields of anthropology: Social Anthropology, Physical Anthropology, Linguistics, and Archaeology.', 'HUM 106', 3, 131, 'Humanities', 1),
(100009, 'General Psychology', 'A survey of the basic principles, theories, and methods of contemporary psychology, including the study of human diversity.', 'HUM 107', 3, 131, 'Humanities', 1),
(100010, 'Introduction to Sociology', 'Scientific study of sociological concepts, theories, processes, and methods used in understanding contemporary human behavior in group interaction.', 'HUM 108', 3, 131, 'Humanities', 1),
(100011, 'Enjoyment of Music', 'Designed to develop an understanding of musical principles and techniques for listening to music. ', 'MUS 101', 3, 132, 'Music', 1),
(100012, 'Theatre Survey', 'Overview of the art and craft of the theatre.', 'MUS 102', 3, 132, 'Music ', 1),
(100013, 'Survey of Rock Music', 'Rise of rock music to prominence, and its impact on audience reception.', 'MUS 103', 3, 132, 'Music', 1),
(100014, 'American Popular Music, 1840s-present', 'Musical and cultural development of popular music in the United States from the 1840s to the present. ', 'MUS 104', 3, 132, 'Music', 1),
(100016, 'Evolution of Jazz', 'Survey of jazz literature and performance.', 'MUS 105', 3, 132, 'Music ', 1),
(100017, 'Music of the World', 'Music in cross-cultural context. Relation of music to religion and society.\r\n ', 'MUS 106', 3, 132, 'Music', 1),
(100018, 'World Literature', 'Poetry, prose, and drama selected from ancient Hebrew, Greek, and Oriental literature and from that of Renaissance Europe.', 'HUM 109', 3, 131, 'Humanities', 1),
(100019, 'World Literature II', 'Readings from Moliere, Voltaire, Goethe, Pushkin, Balzac, Tolstoy, Ibsen, Mann, Kafka, Camus, and others.', 'HUM 110', 3, 131, 'Humanities', 1),
(500024, 'Computational Molecular Biology', 'This advanced course covers the application of machine learning and modeling techniques to biological systems. Topics include gene structure, recognition of DNA and protein sequence patterns, classification, and protein structure prediction.', 'BGE 408', 3, 125, 'Biogenetics', 2);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `course`
--
ALTER TABLE `course`
  ADD PRIMARY KEY (`Course_ID`),
  ADD KEY `cdept_id` (`CDeptID`);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `course`
--
ALTER TABLE `course`
  ADD CONSTRAINT `cdept_id` FOREIGN KEY (`CDeptID`) REFERENCES `department` (`Department_ID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
